version: "3.8"

services:
  django_app:
    build:
      context: ./django_app
    ports:
      - "8000:8000"
    volumes:
      - ./django_app:/app
    environment:
      - DJANGO_SETTINGS_MODULE=nc_app.settings
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=dbname
    # depends_on:
    #   - db

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/cgi-bin:/usr/lib/cgi-bin
    depends_on:
      - django_app

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: dbname
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
